all:
	g++ write_only_vertices.cpp ../../myincludes/tiny_obj_loader.cpp \
	../../myincludes/obj_writer.cpp -o write_only_vertices.out
	./write_only_vertices.out
debug:
	g++ -g write_only_vertices.cpp ../../myincludes/tiny_obj_loader.cpp \
	../../myincludes/obj_writer.cpp -o write_only_vertices.out
	./write_only_vertices.out
