all:
	g++ tiny_obj_loader_example.cpp tiny_obj_loader.cc obj_writer.cc -o tiny_obj_loader
	./tiny_obj_loader
debug:
	g++ -g tiny_obj_loader_example.cpp tiny_obj_loader.cc obj_writer.cc -o tiny_obj_loader
	./tiny_obj_loader