all:
	g++ tiny_obj_loader_example.cpp ../../myincludes/tiny_obj_loader.cpp \
	../../myincludes/obj_writer.cpp -o tiny_obj_loader.out
	./tiny_obj_loader.out
debug:
	g++ -g tiny_obj_loader_example.cpp ../../myincludes/tiny_obj_loader.cpp \
	../../myincludes/obj_writer.cpp -o tiny_obj_loader.out
	./tiny_obj_loader.out
